name: Auto approve

on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'ricci69'
    steps:
      - uses: hmarr/auto-approve-action@v3
        with:
          review-message: "Auto approved automated PR"

# TODO: I need to create an authentication token          
#      - uses: alexwilson/enable-github-automerge-action@main  
#        with:
#          github-token: "${{ secrets.GITHUB_TOKEN }}"
